name: Selenium 101 Tests

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu image for the runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to the latest version of the checkout action

    - name: Set up Node.js
      uses: actions/setup-node@v3  # Set up Node.js environment
      with:
        node-version: '20'  # Use the latest stable version of Node.js (20.x)

    - name: Install dependencies
      run: |
        npm install -g npm  # Ensure npm is up to date
        npm install         # Install project dependencies

    - name: Run selenium tests
      run: npm run test:parallel  # Run the tests
